### PR TITLE
OFF-CAMPUS OPPORTUNITY BACKEND INTEGRATION & LOGIN-NAVIGATION

### PR DESCRIPTION
**Pull request by Sheetal-04**

### CODE REVIEW

**Comment by KingAman26** [comment]
Screenshot 2024-04-14 at 10 42 17 PM
Fix this

**Comment by AmanGupta2626** [comment]
Everything appears to be in order to me. Simply remove the toast BOOKMARK AT YOUR OWN PLACE that appears each time I visit the opportunity page.

**Comment by Sheetal-04** [comment]
> Everything appears to be in order to me. Simply remove the toast BOOKMARK AT YOUR OWN PLACE that appears each time I visit the opportunity page.

Ohk !! I'll remove it .

**Comment by Sheetal-04** [comment]
> > Everything appears to be in order to me. Simply remove the toast BOOKMARK AT YOUR OWN PLACE that appears each time I visit the opportunity page.
> 
> Ohk !! I'll remove it .

DONE✅

**Comment by KingAman26** [comment]
> [!IMPORTANT]
> Looking good now

**Review by AmanGupta2626 — APPROVED** [review]

**Review by Nandani-Paliwal — APPROVED** [review]

**Pull request merged**
