### PR TITLE
Setting Page

### PR DESCRIPTION
**Pull request by AmanGupta2626**

### CODE REVIEW

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
1. Title & Tagline is not going better for the settings page instead of these please put 
**_Account Settings Hub: Navigate Your Options_** 
**_Personalize Your Account: Tailor Your Experience to Perfection_**
Also look into the other component for title tagline which will fix the margin etc for you !!

2. Please increase the **_font-size_** of the heading `Change Profile Picture` and also make the alignment properly put the buttons at last & image at start  .
image

3.In this section ->

1.Correct the spelling **_Information_**
2.Same as above  increase the **_font-size_** of the heading .
3.I'll suggest that `First Name ` & `Last Name` field should be in the same row.
4.Change the label-style **_font-semibold_** & **_text-base_**
5.In Gender Set default value 'Choose Your Gender' make that disabled
6.In about section I would say use `textarea ` instead of `input` tag.
image

4. See the padding difference in the edit profile section & in the change password section .Please give equal padding in both . also add that  **Required field code** in both the fields.
image

5.Correct the delete section content !!
6.APi is working correctly✅.
7.One thing more we will add kind of option tab type so that user doesn't need to scroll for the particular settings because when resume backend will be done then settings options will be much more .Please look into the figma file i have sent you but for now please correct these things .
Figma File link (For Future Reference ,After Resume Backend Done) -> 
[https://www.figma.com/file/JTlygEoUSUGDswg9Xu3Tfp/Settings-dashboard-ui-design-%7C-daily-ui-007-(Community)?type=design&node-id=0%3A1&mode=design&t=MbIbUAUdb5kmOYS6-1](url)
(ONLY FOR TAB PART NOT FOR OTHER PART )

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
image
On smaller screen there is no padding  !!

image

Also look into the margin/gap in y on smaller screen .Please look into each aspect !!

**Comment by AmanGupta2626** [comment]
Done, I do not see the use for that required option , as user will not need to update their password.
image
On my screen it is looking in this way & please look into the smaller screen look for gap & all !!

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
image

1. Just Please look into the heading `Profile Information` & `Password` make the classes same because in small screen **_Profile Information_** heading size is small then the password .
2. Like Change Password box put the buttons at the center in small screen.
3. Just please look into the mt for gender it seems little lesser than the others.
4.  Same Make the heading at center in small screen .
image
5. Please also look into that `eye` make that in center  and also add that **_required code_** in the label
image
6. Please also add a `Pattern check(VALIDATION)` so that password validation can be uniform at every place (Refer login & signup).

else everything looks on point .

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
Still some requested changes are remaining !!

**Review by Sheetal-04 — APPROVED** [review]
✅ Looks accurate  !!

**Pull request merged**
