### PR TITLE
feat: oncampus opportunity listed

### PR DESCRIPTION
**Pull request by Nandani-Paliwal**

### CODE REVIEW

**Comment by Sheetal-04** [comment]
1. I have published a new opportunity (TCS) after publishing that is coming at end instead of this new document should be visible at first because suppose there are 1000 opportunities and new data will be added at last i think that will not be a good option .
2. image
3. Look in this when the mode is "ON-LINE" the meet-link is not provided (Should be visible & also should only be active on that particular time)
4. Also look into the "Mode" that is visible at location place and location is not visible(In others it is visible but there mode is not visible ).
5.Also in this data (TCS) i have included  "Opportunity Extra Details" but that is also not included in the opportunity card.
6.On Submit that modal will be changed because we are asking for the update your things with 2 options "Apply" & "Update Your Details"
7.When we are bookmarking any opportunity first after bookmarked change the status from "SAVE" to "Bookmarked" so that it can not be bookmarked again and also make the button disable after bookmark if you don't want to un-bookmark from there or you can same implement with the bookmark icon at the top if you want ( Whatever you think will look more nicer )
8. In The filter section Instead of Tags just give it some other name and also When the no of tags become larger that is taking lot of space ,can we think of another UI may be dropdown or Can use `details `tag so that we can open and close that may be look better and also if the opportunity is expired so i think we should also remove the respective tags that will help us in minimizing the space same like bookmark. (Can do something dropdown containing search because tags can exist in large number )
9. Also add a filter for date so that opportunities can be shown suppose last 7 days , Last 14 Days what we were discussing.
image
10.image
*In Bookmark section when we remove any opportunity that is showing toast "Un-Bookmarked" but data is not changing on refresh we can see that the opportunity is deleted .(Check your function call this is happening because of the asynchronous nature after successful response show that).
*Also look in bookmark when mode is "ON-LINE" still the link is not given and implement same as Opportunity (Disable etc.)
*I think in expired opportunity "Drive ends" will be "Drive ended".
*Same as opportunity mode is visible in place of location and location is not visible.
*Can add a navigate option kind of button to see the full details of that opportunity (navigate to the my opportunity or something else you wanna do in UI acc. to you).
* image
* Look into this when i clicked on tag UI is behaving like this . and also the related data is not seen.
*Please also correct the alignment at the right side !
> [!NOTE]
> I think it is wrong we should show loading instead of this this will look when there are no opportunities not on loading.
image

> [!TIP]
> Can we add a code of small countdown on the opportunity at the top which will show the remaining time ,I think that will look good .Do at last just a thought.


### ADMN DASHBOARD->

- I am not able to see the "My Opportunities" option in the admin sidebar.
- The Code will completely re-used just the data will differ from the student and also some few options will be included like Edit ,Delete.
- Just Conditional Render these things that component will also be completed.

**Comment by Nandani-Paliwal** [comment]
> 1. I have published a new opportunity (TCS) after publishing that is coming at end instead of this new document should be visible at first because suppose there are 1000 opportunities and new data will be added at last i think that will not be a good option .
> 2. image
> 3. Look in this when the mode is "ON-LINE" the meet-link is not provided (Should be visible & also should only be active on that particular time)
> 4. Also look into the "Mode" that is visible at location place and location is not visible(In others it is visible but there mode is not visible ).
>    5.Also in this data (TCS) i have included  "Opportunity Extra Details" but that is also not included in the opportunity card.
>    6.On Submit that modal will be changed because we are asking for the update your things with 2 options "Apply" & "Update Your Details"
>    7.When we are bookmarking any opportunity first after bookmarked change the status from "SAVE" to "Bookmarked" so that it can not be bookmarked again and also make the button disable after bookmark if you don't want to un-bookmark from there or you can same implement with the bookmark icon at the top if you want ( Whatever you think will look more nicer )
> 5. In The filter section Instead of Tags just give it some other name and also When the no of tags become larger that is taking lot of space ,can we think of another UI may be dropdown or Can use `details `tag so that we can open and close that may be look better and also if the opportunity is expired so i think we should also remove the respective tags that will help us in minimizing the space same like bookmark. (Can do something dropdown containing search because tags can exist in large number )
> 6. Also add a filter for date so that opportunities can be shown suppose last 7 days , Last 14 Days what we were discussing.
>    image
>    10.image
>    *In Bookmark section when we remove any opportunity that is showing toast "Un-Bookmarked" but data is not changing on refresh we can see that the opportunity is deleted .(Check your function call this is happening because of the asynchronous nature after successful response show that).
>    *Also look in bookmark when mode is "ON-LINE" still the link is not given and implement same as Opportunity (Disable etc.)
>    *I think in expired opportunity "Drive ends" will be "Drive ended".
>    *Same as opportunity mode is visible in place of location and location is not visible.
>    *Can add a navigate option kind of button to see the full details of that opportunity (navigate to the my opportunity or something else you wanna do in UI acc. to you).
> 
> * image
> * Look into this when i clicked on tag UI is behaving like this . and also the related data is not seen.
>   *Please also correct the alignment at the right side !
> 
> Note
> 
> I think it is wrong we should show loading instead of this this will look when there are no opportunities not on loading. image
> 
> Tip
> 
> Can we add a code of small countdown on the opportunity at the top which will show the remaining time ,I think that will look good .Do at last just a thought.
> 
> ### ADMN DASHBOARD->
> * I am not able to see the "My Opportunities" option in the admin sidebar.
> * The Code will completely re-used just the data will differ from the student and also some few options will be included like Edit ,Delete.
> * Just Conditional Render these things that component will also be completed.

👀 Sheetal I just asked to check if the opportunity tags are ok and this is what we need 🙁 , the rest of the work is still in progress.

**Comment by Sheetal-04** [comment]
> l I just asked to check if the opportunity tags are ok and this is what we need 🙁 , the rest of the work is still in progress.

I thought you asked me to review but opportunity card is complete so these changes (maximum) are related to that card .I know Admin thing in WIP but i just wrote that down as info for you !!

**Comment by Nandani-Paliwal** [comment]
> > l I just asked to check if the opportunity tags are ok and this is what we need 🙁 , the rest of the work is still in progress.
> 
> I thought you asked me to review but opportunity card is complete so these changes (maximum) are related to that card.I know Admin thing in WIP but i just wrote that down as info for you !!

Nope the even the on-campus opportunity card as well as the bookmarked page for on-campus both them are still in  WIP, the work for them is still not finished from my end that's why I haven't removed the PR from the draft PR, but it's ok I will ping you after finishing it up.

**Comment by Sheetal-04** [comment]
> > > l I just asked to check if the opportunity tags are ok and this is what we need 🙁 , the rest of the work is still in progress.
> > 
> > 
> > I thought you asked me to review but opportunity card is complete so these changes (maximum) are related to that card.I know Admin thing in WIP but i just wrote that down as info for you !!
> 
> Nope the even the on-campus opportunity card as well as the bookmarked page for on-campus both them are still in WIP, the work for them is still not finished from my end that's why I haven't removed the PR from the draft PR, but it's ok I will ping you after finishing it up.

Hmm Ok !! I just thought you told me to review that's why i did ,Just a mis-communication !!

**Comment by Sheetal-04** [comment]
**OPPORTUNITY RECORD :**

- On an active opportunity like this here also add a timer clock .
image
- You can make the enrolled Students button in a single line and others in the same row because that is looking little odd on small screen & also please try to change that button color from yellow to something else or if you are keeping that on hover little different shade of that can go but it is not going same for light theme ,just try little different option for that btn.
image
- Just make that bullet point same in size irrespective of the content length you can see that in opportunity panel where i have used that icon.
image
image
- Just focus on the timings of the system and the opportunity i have set the time just 3 min before but not able to see the link in the admin opportunity (i guess that logic is missing here) and i think for admin link should be visible all the time so just add the `Join the drive` here without disabling so that  on click admin can directly go to that platform !!
image
- As per discussion filter option should not be there on small screen .
image
- If company name is little moderate then expired tag is overlapping with the name .For your help you can also see the dimensions same you can fix the job-location thing.
image
image

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
Later I'll get time will review other pages too!!

**Comment by Nandani-Paliwal** [comment]
> You can make the enrolled Students button in a single line and others in the same row because that is looking little odd on small screen & also please try to change that button color from yellow to something else or if you are keeping that on hover little different shade of that can go but it is not going same for light theme ,just try little different option for that btn.

we should maintain the consistency in the project and you have only applied this color theme in one of the button that's why used this, still if you want to change it, then please specify the color that I should apply.

**Comment by Sheetal-04** [comment]
### OPPORTUNITY RECORD ->

- You have added the timer that is ryt but i think by mistake you have just copied the bookmarked code also on hover on timer there is an cursor pointer is coming and also clicking unwanted API call is going .
- Here I have also mentioned above that please keep the join the drive option for admin that is missing because in some platform like webex we can set come configurations before meeting so that we can give access to admin for that .
image
- Nandini can we just have tags for the tablet also because see i think still we can show here in my pov that can change to lg .
image
- I think location alignment issue is still there .
image
-else  this component looks good to me .Please also consider the oral discussion of ours on color and that enrolled student one.

**Comment by Sheetal-04** [comment]
> ### OPPORTUNITY RECORD ->
> * You have added the timer that is ryt but i think by mistake you have just copied the bookmarked code also on hover on timer there is an cursor pointer is coming and also clicking unwanted API call is going .
> * Here you have kept the join the drive option for admin but please don't make it disable for admin in some platform like webex we can set come configurations before meeting so that we can give access to admin for that and also why this button is visible in one active opportunity.
image
image

> * Nandini can we just have tags for the tablet also because see i think still we can show here in my pov that can change to lg .
>   image
> * I think location alignment issue is still there .
>   image
>   -else  this component looks good to me .Please also consider the oral discussion of ours on color and that enrolled student one.

**Comment by Sheetal-04** [comment]
### MY BOOKMARKED
- We can remove the disable thing from applied i think that is a status ryt so after disable that is not looking fine !!
image
- I think can we just have the same color in all the opportunity details because like in offcampus bookmark that is looking good .Just keep the opportunity name in that color (e.g., Marketing Intern)
- Just can we fix this like in small screen same last button can be in the next row and also other thing like location etc. Just little bit figure that out i know that is fine for this opportunity but suppose if a location is big or opportunity then we can have issue may be in my pov just see if that can be fixed  !!
image
- I have applied for this opportunity but the status is still apply now .
image
- Just see the opportunity panel header thing i have just added some properties may be we can also do this better 
image
Look at it opportunity panel :
image
Dimensions of both are at this point : 
image

📌Rest everything is on point !! After these changes we can lock this component.

**Comment by Sheetal-04** [comment]
### MY OPPORTUNITIES ->
image
Can we have tag for our tablet mode !!
- Here also can we do this just change the status to applied and don't make it disable so that that can look better or i just wanna know that i am not able to un-bookmark from here .Why??
image
- Can we fix the location thing if location is like we have added in some of our opportunity so for that .
image
- Look at it !! Both the opportunities are applied also  `join the drive` button is visible but i think you have added opposite logic if the opportunity is  "ON-LINE" then join the drive button will be visible .Here Taxtron one is offline and button is visible there  (After that only i will be able to check that meeting link thing by changing the system time)
image
image

📌Rest everything is on point !! After these changes we can lock this component and please remind me after these changes to check that meeting link thing rest is on-point .

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
Changes Requested !!

**Comment by Nandani-Paliwal** [comment]
> why this button is visible in one active opportunity.

I have checked from my side but was not able to find any bug in the code

**Comment by Sheetal-04** [comment]
> > why this button is visible in one active opportunity.
> 
> I have checked from my side but was not able to find any bug in the code

No that is fine that will be in one active but it will depend upon opportunity is going to held Offline or online so you have added the opposite logic where off-line it is showing join the drive but that shouldn't be the case

**Comment by Nandani-Paliwal** [comment]
> We can remove the disable thing from applied i think that is a status ryt so after disable that is not looking fine !!

that is not status sheetal, that is a button, and once a user applied on an opp the button will become disable

**Comment by Nandani-Paliwal** [comment]
> I think can we just have the same color in all the opportunity details because like in offcampus bookmark that is looking good .Just keep the opportunity name in that color (e.g., Marketing Intern)

If I got your right then , opportunity name is in blue color only sheetal, we have some extra fields in on-campus that is "Role" and "package" and to highlight them from other details have given them black and white color respectively according to themes.
If I got your wrong then please explain the review

**Review by Sheetal-04 — APPROVED** [review]

**Pull request merged**
