### PR TITLE
WIP:Student Analytic

### PR DESCRIPTION
**Pull request by Sheetal-04**

### CODE REVIEW

**Comment by AmanGupta2626** [comment]
Screenshot 2024-05-02 at 11 53 56 AM
Screenshot 2024-05-02 at 11 53 42 AM

**Comment by AmanGupta2626** [comment]
***See the responsiveness rest is looking good***
--

**Comment by Sheetal-04** [comment]
> ## _**See the responsiveness rest is looking good**_
I said just check the flow of UI can we keep it in this way or not !! I have just placed everything to show it to Sir !! Work will be done on this.

**Comment by Nandani-Paliwal** [comment]
image
give color primary-500 to the text which is in typewriter effect, this will give more emphasis on that text, and the one which is in no animation give it black only.... or you can also try with some other color combo

**Comment by Nandani-Paliwal** [comment]
image

The button is not at center

**Comment by Nandani-Paliwal** [comment]
We can also add section for on campus bookmarked, like we have added one for off campus, similarly one for like giving stats of active oncampus job bookmarked and applied

**Comment by Nandani-Paliwal** [comment]
use light color for dark theme
image

if using gray shade for dark theme then use gray shade only for light theme also, or can use black for light theme and white for dark theme
image

**Review by Nandani-Paliwal — APPROVED** [review]

**Pull request merged**
