### PR TITLE
Features Added : Opportunities Listing & bookmarked

### PR DESCRIPTION
**Pull request by Sheetal-04**
I have added 2 extra options in dropdown menu only for the review of 2 PAGES Error Page & No Opportunities .Later on after successful review i will remove these two  and little bit styling will be done on the pagination .

### CODE REVIEW

**Comment by vishwajeet112** [comment]
Review and Others are same now

**Review by Nandani-Paliwal — CHANGES_REQUESTED** [review]
Screenshot from 2024-03-04 21-50-11
Screenshot from 2024-03-04 21-50-33


Fix alignment and padding issues in the text content of opportunity card

**Review by AmanGupta2626 — DISMISSED** [review]

**Comment by Nandani-Paliwal** [comment]
image

**Comment by Nandani-Paliwal** [comment]
image

**Review by Nandani-Paliwal — CHANGES_REQUESTED** [review]
Add panding to the main heading of the page

**Comment by Nandani-Paliwal** [comment]
image

Dont give min-width in the opportunity card, or you can also try to use some other format for the information fiven beacause that one line gap in some cards due to big name of organization will look odd. 

Screenshot from 2024-03-05 09-38-05

Try different combinations with heading of the page, increase the font size, use primary color + black color in the heading

**Comment by KingAman26** [comment]
White color border in right side  is showing when we are decreasing the width below 375

**Comment by KingAman26** [comment]
Screenshot 2024-03-05 at 10 48 57 AM

**Comment by Nandani-Paliwal** [comment]
image
reduce the gap between icons and start date, end date

**Comment by Nandani-Paliwal** [comment]
Screenshot from 2024-03-05 13-53-53


make the cards equal, 
why there is a line gap in some cards ?

**Comment by Nandani-Paliwal** [comment]
Screenshot from 2024-03-05 13-51-48


center align all the elements in small screen

**Comment by Sheetal-04** [comment]
> Screenshot from 2024-03-05 13-51-48
> 
> center align all the elements in small screen

No these items  are not looking good in  center.

**Comment by Sheetal-04** [comment]
> Screenshot from 2024-03-05 13-53-53
> 
> make the cards equal, why there is a line gap in some cards ?

Which line gap you are talking about ? i am not able to see this .

**Review by Nandani-Paliwal — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
