### PR TITLE
Setting Page

### PR DESCRIPTION
**Pull request by AmanGupta2626**

### CODE REVIEW

**Comment by Sheetal-04** [comment]
image
- [x] Here you didn't set the default check that if link already exists in DB that should be visible here too !! (One more thing i think if possible that in linkedin section if we can filter it out that person is giving linkedin like i gave random url and it was accepted  (Optional but please try).
- [ ] Please maintain consistency in the whole UI here you have changes the color of label etc. please keep it similar. just use the predefined class.
image
- [x] Also make the button identical in size see your above code in password section for buttons
- [x] In internship section please add a check on the date i have entered the data of future it accepted that.
image
- [ ] Also add required symbol on start date too.
- [ ] See!! the placeholder text is wrong add a dummy kind of link in placeholder `https://certification-link`
image
- [ ] Here i'll suggest please write "Choose Your education board" and also add the short form like (CBSC) too.
- [ ] I think it will be better if you write down some logic so that if "HighSchool" and "Intermediate" is chosen then Bundelkhand University should not be in the option or you can keep it in option but can make that disablesame goes for Graduation disable other options .
- [ ] Also when i am entering only "Your qualifications " and other things not filling board backend is throwing error that is fine but also add a check on frontend  using react-hook-form.
- [ ] In percentage it should accept only number not everything. also change the placeholder should be kind of i.e., 80
image
- [ ] In the project section i think enhance the UI of techstack and also there should be an option to remove that .
image
- [ ] Same for this section i think enhance the UI of skills and also there should be an option to remove that .
- [ ] Remove that required thing from skills because nothing is required here.
- [ ] Also the third field you have mentioned "Internship Type" that should be different not this you can add something "You are looking for" kind of...
- [ ] There should be an another option instead of not-specified that should be "Hybrid"
- [ ] Here you also gave 2 defaults make it one only  same in internship type.
image
- [ ] Why on clicking in achievements and work experience it is going to my profile it should call the API please check it out
> [!NOTE]
> UI is looking fine to me but I'll check deeply after resolving these logical bugs , First resolve these !!

**Comment by Sheetal-04** [comment]
image
Look into this !!

**Comment by Sheetal-04** [comment]
Done !!

**Review by Sheetal-04 — DISMISSED** [review]
DONE!!

**Review by Nandani-Paliwal — CHANGES_REQUESTED** [review]
image


- we should use different logo color here cause at first it seems like, `in Linkedin` 
- can add twitter in brackets in X field label to maintain consistency

**Review by Nandani-Paliwal — COMMENTED** [review]
Once I upload my social link,it should render here, the fields got reset
image

**Review by Nandani-Paliwal — COMMENTED** [review]
button color is not consistent
image

**Comment by AmanGupta2626** [comment]
> Once I upload my social link,it should render here, the fields got reset image

**because Sheetal will preserve the redux state later on, and it will reflect**

**Review by Nandani-Paliwal — CHANGES_REQUESTED** [review]
Resolve the conflicts

**Review by Nandani-Paliwal — DISMISSED** [review]
Screenshot from 2024-05-04 12-55-49

svg icon is not properly align with the text,
- since we have used shade of gray for dark mode, we should use lighter gray shade in light mode as well

**Comment by Nandani-Paliwal** [comment]
REST Looks good to me !

**Comment by AmanGupta2626** [comment]
> Screenshot from 2024-05-04 12-55-49
> 
> svg icon is not properly align with the text,
> 
> * since we have used shade of gray for dark mode, we should use lighter gray shade in light mode as well
Sheetal defines these classes in the global.css .I am unable to do anything with these predefined classes in the CSS file.

**Review by Sheetal-04 — APPROVED** [review]

**Pull request merged**
