### PR TITLE
feat: added some more sections

### PR DESCRIPTION
**Pull request by Nandani-Paliwal**

### CODE REVIEW

**Comment by AmanGupta2626** [comment]
Sadik sir's testonial is not matching our theme fix it

**Comment by AmanGupta2626** [comment]
Dark mode is not working on chatbot

**Comment by Nandani-Paliwal** [comment]
> Dark mode is not working on chatbot

That is advanced feature of crisp and can be done if we have it's subscription.

**Comment by Nandani-Paliwal** [comment]
> Sadik sir's testonial is not matching our theme fix it

That shade is just a darker shade  of our primary colour not out of the theme and done according to the UI appearance.

**Comment by AmanGupta2626** [comment]
> > Sadik sir's testonial is not matching our theme fix it
> 
> That shade is just a darker shade of our primary colour not out of the theme and done according to the UI appearance.

but it is not matching our theme......

**Review by Sheetal-04 — APPROVED** [review]

**Pull request merged**
