### PR TITLE
feat: opportunity page of the dashboard 

### PR DESCRIPTION
**Pull request by Nandani-Paliwal**

### CODE REVIEW

**Review by Sheetal-04 — CHANGES_REQUESTED** [review]
1.Add  Tabs to filter the data as we discussed at the top so that opportunity based on the type can be seen.
2.If opportunity Expired then instead of Closing on it should be Closed on!!
3.Please seperate the data on the basis of date ,you can try it with add a <hr/> tag and also mention date  (On which opportunity is bookmarked).
4.Please Check responsiveness !!
image
5.I suggest ,in my pov opportunity Name should be in little large font than description ,that will look good maybe.
6.Please also give some title at the top as we have used in our opportunities that will give a nice look to it ,looking empty otherwise.
7. I am going to add the description in DB and also the Date on which the opportunity has been bookmarked.
8.One thing more please seperate the backend api call from the frontend file becuase that's why we have made the operations folder so that backend & frontend can be completely sepearte for the better redability & maintenance of code.

**Comment by AmanGupta2626** [comment]
Screenshot 2024-04-03 at 2 10 00 AM
Fix navbar

**Comment by AmanGupta2626** [comment]
Clicking the expired button gives you the opportunity to view the apply option that is displayed. fix it

**Comment by AmanGupta2626** [comment]
@
Screenshot 2024-04-03 at 2 19 39 AM
Its not looking good , you can give "description" more space

**Comment by Nandani-Paliwal** [comment]
> Please seperate the data on the basis of date ,you can try it with add a

explain this please.

**Comment by Nandani-Paliwal** [comment]
> Add Tabs to filter the data as we discussed at the top so that opportunities based on the type can be seen.

I guess we have discussed to add the toggle to show the opportunities on the type of campus I,.e on-campus or off-campus

**Review by Sheetal-04 — APPROVED** [review]

**Pull request merged**
